version: 1.0
publish: app
services:
  app:
    command: "yarn install && yarn build"
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    ports:
      - container: 1234
        public: 80
